### ISSUE TITLE
Licensing incompatible

### ISSUE THREAD

**Issue by noirscape** [DiamondIceNS/StarlightGlimmer#1]
The licenses you use for this repository are WTFPL, CC0 and GPLv3.

The GPLv3 is not compatible with WTFPL and CC0, since GPLv3 is copyleft, which means that any code that uses GPLv3 as a library or uses it in general must also be licensed under GPLv3.

Your options here are to either remove the GPLv3 code from the repository (animotes) or to relicense the entire project to GPLv3.

**Comment by astronautlevel2** [comment]
WTFPL is compatible with the GPLv3 and thus this is irrelevant.

**Comment by DiamondIceNS** [comment]
I have updated my LICENSE.txt to make it abundantly clear that this repository distributed as a unit with animotes.py is indeed done so under GPLv3.

The remainder of my code that functions without animotes shall remain under CC0, which is compatible with GPLv3.
